[package]
name = "font"
version = "0.1.0"
authors = ["Sahil Parikh <sahil.parikh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
colored = "2.0.0"